import * as vscode from 'vscode';

export class PlanInputView implements vscode.WebviewViewProvider {
  private view?: vscode.WebviewView;
  constructor(private readonly onPlan: (input: string, sql?: string) => void) {}
  resolveWebviewView(view: vscode.WebviewView): void {
    this.view = view;
    view.webview.options = { enableScripts: true };
    view.webview.html = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-foreground);padding:12px 10px;margin:0}h1{font-size:18px;margin:4px 0 7px}p{color:var(--vscode-descriptionForeground);line-height:1.45;font-size:12px;margin:0 0 15px}.hero{border:1px solid var(--vscode-widget-border);border-radius:8px;padding:12px;margin-bottom:12px;background:var(--vscode-editorWidget-background)}textarea{width:100%;height:180px;resize:vertical;box-sizing:border-box;background:var(--vscode-textCodeBlock-background);color:var(--vscode-editor-foreground);border:1px solid var(--vscode-input-border);border-radius:5px;padding:9px;font:12px var(--vscode-editor-font-family);outline:none}textarea:focus{border-color:var(--vscode-focusBorder)}textarea.error{border-color:var(--vscode-inputValidation-errorBorder,#be1100)}.field-error{color:var(--vscode-inputValidation-errorForeground,#f48771);font-size:11px;margin:0 0 9px}.field-label{display:block;font-size:11px;margin:11px 0 4px;color:var(--vscode-descriptionForeground)}button{width:100%;margin-bottom:9px;border:0;border-radius:5px;padding:9px;background:var(--vscode-button-background);color:var(--vscode-button-foreground);font-weight:600;cursor:pointer}button:hover{background:var(--vscode-button-hoverBackground)}.tip{font-size:11px;margin-top:14px}</style></head><body><section class="hero"><h1>SQL Plan Visualizer</h1><p>See what your query is really doing. Paste an EXPLAIN plan and turn it into a clear execution story.</p><button id="visualize">Visualize plan</button><p class="field-error" id="error" hidden></p><textarea id="plan" autofocus placeholder="Paste EXPLAIN output here..."></textarea><label class="field-label" for="sql">SQL query (optional, shown next to the plan)</label><textarea id="sql" placeholder="Paste your SQL query here..."></textarea></section><p class="tip">Tip: select an EXPLAIN result in the editor and use the database icon in the editor toolbar.</p><script>const vscode=acquireVsCodeApi();const input=document.getElementById('plan');const sql=document.getElementById('sql');const error=document.getElementById('error');const clearError=()=>{error.hidden=true;input.classList.remove('error')};const send=()=>{if(!input.value.trim()){error.textContent='Missing EXPLAIN output. Paste the EXPLAIN plan before visualizing.';error.hidden=false;input.classList.add('error');input.focus();return}clearError();vscode.postMessage({type:'visualize',input:input.value,sql:sql.value.trim()||undefined})};document.getElementById('visualize').addEventListener('click',send);input.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter')send()});input.addEventListener('input',clearError);</script></body></html>`;
    view.webview.onDidReceiveMessage(message => { if (message.type === 'visualize' && typeof message.input === 'string') {this.onPlan(message.input, typeof message.sql === 'string' ? message.sql : undefined);} });
  }
  focus(): void { this.view?.show?.(true); }
}
